// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/ride.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ffa51ead3a087cb, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type AuthRequest struct {
	AuthToken            string   `protobuf:"bytes,1,opt,name=authToken,proto3" json:"authToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ffa51ead3a087cb, []int{1}
}

func (m *AuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequest.Unmarshal(m, b)
}
func (m *AuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequest.Marshal(b, m, deterministic)
}
func (m *AuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequest.Merge(m, src)
}
func (m *AuthRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRequest.Size(m)
}
func (m *AuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequest proto.InternalMessageInfo

func (m *AuthRequest) GetAuthToken() string {
	if m != nil {
		return m.AuthToken
	}
	return ""
}

type RegisterRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Balance              uint32   `protobuf:"varint,3,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ffa51ead3a087cb, []int{2}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterRequest) GetBalance() uint32 {
	if m != nil {
		return m.Balance
	}
	return 0
}

type RegisterResponse struct {
	AuthToken            string   `protobuf:"bytes,1,opt,name=authToken,proto3" json:"authToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ffa51ead3a087cb, []int{3}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetAuthToken() string {
	if m != nil {
		return m.AuthToken
	}
	return ""
}

type LoginRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ffa51ead3a087cb, []int{4}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	AuthToken            string   `protobuf:"bytes,1,opt,name=authToken,proto3" json:"authToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ffa51ead3a087cb, []int{5}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetAuthToken() string {
	if m != nil {
		return m.AuthToken
	}
	return ""
}

type AddFundsRequest struct {
	AuthToken            string   `protobuf:"bytes,1,opt,name=authToken,proto3" json:"authToken,omitempty"`
	Amount               uint32   `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddFundsRequest) Reset()         { *m = AddFundsRequest{} }
func (m *AddFundsRequest) String() string { return proto.CompactTextString(m) }
func (*AddFundsRequest) ProtoMessage()    {}
func (*AddFundsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ffa51ead3a087cb, []int{6}
}

func (m *AddFundsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddFundsRequest.Unmarshal(m, b)
}
func (m *AddFundsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddFundsRequest.Marshal(b, m, deterministic)
}
func (m *AddFundsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddFundsRequest.Merge(m, src)
}
func (m *AddFundsRequest) XXX_Size() int {
	return xxx_messageInfo_AddFundsRequest.Size(m)
}
func (m *AddFundsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddFundsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddFundsRequest proto.InternalMessageInfo

func (m *AddFundsRequest) GetAuthToken() string {
	if m != nil {
		return m.AuthToken
	}
	return ""
}

func (m *AddFundsRequest) GetAmount() uint32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type AddFundsResponse struct {
	Balance              uint32   `protobuf:"varint,1,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddFundsResponse) Reset()         { *m = AddFundsResponse{} }
func (m *AddFundsResponse) String() string { return proto.CompactTextString(m) }
func (*AddFundsResponse) ProtoMessage()    {}
func (*AddFundsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ffa51ead3a087cb, []int{7}
}

func (m *AddFundsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddFundsResponse.Unmarshal(m, b)
}
func (m *AddFundsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddFundsResponse.Marshal(b, m, deterministic)
}
func (m *AddFundsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddFundsResponse.Merge(m, src)
}
func (m *AddFundsResponse) XXX_Size() int {
	return xxx_messageInfo_AddFundsResponse.Size(m)
}
func (m *AddFundsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddFundsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddFundsResponse proto.InternalMessageInfo

func (m *AddFundsResponse) GetBalance() uint32 {
	if m != nil {
		return m.Balance
	}
	return 0
}

type CheckBalanceResponse struct {
	Balance              uint32   `protobuf:"varint,1,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckBalanceResponse) Reset()         { *m = CheckBalanceResponse{} }
func (m *CheckBalanceResponse) String() string { return proto.CompactTextString(m) }
func (*CheckBalanceResponse) ProtoMessage()    {}
func (*CheckBalanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ffa51ead3a087cb, []int{8}
}

func (m *CheckBalanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckBalanceResponse.Unmarshal(m, b)
}
func (m *CheckBalanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckBalanceResponse.Marshal(b, m, deterministic)
}
func (m *CheckBalanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckBalanceResponse.Merge(m, src)
}
func (m *CheckBalanceResponse) XXX_Size() int {
	return xxx_messageInfo_CheckBalanceResponse.Size(m)
}
func (m *CheckBalanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckBalanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckBalanceResponse proto.InternalMessageInfo

func (m *CheckBalanceResponse) GetBalance() uint32 {
	if m != nil {
		return m.Balance
	}
	return 0
}

type PickupBikeRequest struct {
	AuthToken            string   `protobuf:"bytes,1,opt,name=authToken,proto3" json:"authToken,omitempty"`
	Zone                 string   `protobuf:"bytes,2,opt,name=zone,proto3" json:"zone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PickupBikeRequest) Reset()         { *m = PickupBikeRequest{} }
func (m *PickupBikeRequest) String() string { return proto.CompactTextString(m) }
func (*PickupBikeRequest) ProtoMessage()    {}
func (*PickupBikeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ffa51ead3a087cb, []int{9}
}

func (m *PickupBikeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PickupBikeRequest.Unmarshal(m, b)
}
func (m *PickupBikeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PickupBikeRequest.Marshal(b, m, deterministic)
}
func (m *PickupBikeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PickupBikeRequest.Merge(m, src)
}
func (m *PickupBikeRequest) XXX_Size() int {
	return xxx_messageInfo_PickupBikeRequest.Size(m)
}
func (m *PickupBikeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PickupBikeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PickupBikeRequest proto.InternalMessageInfo

func (m *PickupBikeRequest) GetAuthToken() string {
	if m != nil {
		return m.AuthToken
	}
	return ""
}

func (m *PickupBikeRequest) GetZone() string {
	if m != nil {
		return m.Zone
	}
	return ""
}

type MoveRequest struct {
	AuthToken            string   `protobuf:"bytes,1,opt,name=authToken,proto3" json:"authToken,omitempty"`
	Zone                 string   `protobuf:"bytes,2,opt,name=zone,proto3" json:"zone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoveRequest) Reset()         { *m = MoveRequest{} }
func (m *MoveRequest) String() string { return proto.CompactTextString(m) }
func (*MoveRequest) ProtoMessage()    {}
func (*MoveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ffa51ead3a087cb, []int{10}
}

func (m *MoveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveRequest.Unmarshal(m, b)
}
func (m *MoveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveRequest.Marshal(b, m, deterministic)
}
func (m *MoveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveRequest.Merge(m, src)
}
func (m *MoveRequest) XXX_Size() int {
	return xxx_messageInfo_MoveRequest.Size(m)
}
func (m *MoveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MoveRequest proto.InternalMessageInfo

func (m *MoveRequest) GetAuthToken() string {
	if m != nil {
		return m.AuthToken
	}
	return ""
}

func (m *MoveRequest) GetZone() string {
	if m != nil {
		return m.Zone
	}
	return ""
}

type InfoClientResponse struct {
	OnBike               bool     `protobuf:"varint,1,opt,name=onBike,proto3" json:"onBike,omitempty"`
	AtZone               string   `protobuf:"bytes,2,opt,name=atZone,proto3" json:"atZone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InfoClientResponse) Reset()         { *m = InfoClientResponse{} }
func (m *InfoClientResponse) String() string { return proto.CompactTextString(m) }
func (*InfoClientResponse) ProtoMessage()    {}
func (*InfoClientResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ffa51ead3a087cb, []int{11}
}

func (m *InfoClientResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoClientResponse.Unmarshal(m, b)
}
func (m *InfoClientResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoClientResponse.Marshal(b, m, deterministic)
}
func (m *InfoClientResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoClientResponse.Merge(m, src)
}
func (m *InfoClientResponse) XXX_Size() int {
	return xxx_messageInfo_InfoClientResponse.Size(m)
}
func (m *InfoClientResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoClientResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InfoClientResponse proto.InternalMessageInfo

func (m *InfoClientResponse) GetOnBike() bool {
	if m != nil {
		return m.OnBike
	}
	return false
}

func (m *InfoClientResponse) GetAtZone() string {
	if m != nil {
		return m.AtZone
	}
	return ""
}

type Zone struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Bikes                int32    `protobuf:"varint,2,opt,name=bikes,proto3" json:"bikes,omitempty"`
	Capacity             int32    `protobuf:"varint,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Zone) Reset()         { *m = Zone{} }
func (m *Zone) String() string { return proto.CompactTextString(m) }
func (*Zone) ProtoMessage()    {}
func (*Zone) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ffa51ead3a087cb, []int{12}
}

func (m *Zone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Zone.Unmarshal(m, b)
}
func (m *Zone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Zone.Marshal(b, m, deterministic)
}
func (m *Zone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Zone.Merge(m, src)
}
func (m *Zone) XXX_Size() int {
	return xxx_messageInfo_Zone.Size(m)
}
func (m *Zone) XXX_DiscardUnknown() {
	xxx_messageInfo_Zone.DiscardUnknown(m)
}

var xxx_messageInfo_Zone proto.InternalMessageInfo

func (m *Zone) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Zone) GetBikes() int32 {
	if m != nil {
		return m.Bikes
	}
	return 0
}

func (m *Zone) GetCapacity() int32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

type InfoZonesResponse struct {
	Zones                []*Zone  `protobuf:"bytes,1,rep,name=zones,proto3" json:"zones,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InfoZonesResponse) Reset()         { *m = InfoZonesResponse{} }
func (m *InfoZonesResponse) String() string { return proto.CompactTextString(m) }
func (*InfoZonesResponse) ProtoMessage()    {}
func (*InfoZonesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ffa51ead3a087cb, []int{13}
}

func (m *InfoZonesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoZonesResponse.Unmarshal(m, b)
}
func (m *InfoZonesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoZonesResponse.Marshal(b, m, deterministic)
}
func (m *InfoZonesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoZonesResponse.Merge(m, src)
}
func (m *InfoZonesResponse) XXX_Size() int {
	return xxx_messageInfo_InfoZonesResponse.Size(m)
}
func (m *InfoZonesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoZonesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InfoZonesResponse proto.InternalMessageInfo

func (m *InfoZonesResponse) GetZones() []*Zone {
	if m != nil {
		return m.Zones
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "Empty")
	proto.RegisterType((*AuthRequest)(nil), "AuthRequest")
	proto.RegisterType((*RegisterRequest)(nil), "RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "RegisterResponse")
	proto.RegisterType((*LoginRequest)(nil), "LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "LoginResponse")
	proto.RegisterType((*AddFundsRequest)(nil), "AddFundsRequest")
	proto.RegisterType((*AddFundsResponse)(nil), "AddFundsResponse")
	proto.RegisterType((*CheckBalanceResponse)(nil), "CheckBalanceResponse")
	proto.RegisterType((*PickupBikeRequest)(nil), "PickupBikeRequest")
	proto.RegisterType((*MoveRequest)(nil), "MoveRequest")
	proto.RegisterType((*InfoClientResponse)(nil), "InfoClientResponse")
	proto.RegisterType((*Zone)(nil), "Zone")
	proto.RegisterType((*InfoZonesResponse)(nil), "InfoZonesResponse")
}

func init() {
	proto.RegisterFile("proto/ride.proto", fileDescriptor_4ffa51ead3a087cb)
}

var fileDescriptor_4ffa51ead3a087cb = []byte{
	// 518 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0xdf, 0x6e, 0xda, 0x30,
	0x14, 0xc6, 0xc5, 0x20, 0x29, 0x1c, 0x60, 0x0d, 0x5e, 0x57, 0x45, 0x59, 0x35, 0xa1, 0x5c, 0x4c,
	0x48, 0x5b, 0x4d, 0xd5, 0x3e, 0xc0, 0x54, 0xba, 0x76, 0x9a, 0xd4, 0x49, 0x93, 0xb7, 0xab, 0xde,
	0x85, 0xc4, 0x03, 0x2b, 0x60, 0x67, 0xb1, 0xc3, 0xd4, 0x3d, 0xd8, 0x9e, 0x6f, 0xb2, 0x13, 0x92,
	0x2c, 0x20, 0x15, 0xa9, 0x57, 0xf1, 0xe7, 0x3f, 0xdf, 0xf9, 0x38, 0xfe, 0x19, 0x70, 0x92, 0x54,
	0x28, 0x31, 0x4d, 0x59, 0x44, 0xb1, 0x19, 0xfa, 0x47, 0x60, 0xdd, 0xae, 0x13, 0xf5, 0xe8, 0xbf,
	0x87, 0xfe, 0x75, 0xa6, 0x96, 0x84, 0xfe, 0xca, 0xa8, 0x54, 0xe8, 0x0c, 0x7a, 0x41, 0xa6, 0x96,
	0x3f, 0x44, 0x4c, 0xb9, 0xdb, 0x1a, 0xb7, 0x26, 0x3d, 0x52, 0x4d, 0xf8, 0x21, 0x1c, 0x13, 0xba,
	0x60, 0x52, 0xd1, 0x74, 0x7b, 0xc0, 0x83, 0x6e, 0x26, 0x69, 0xca, 0x83, 0x35, 0x2d, 0xf6, 0x97,
	0x5a, 0xaf, 0x25, 0x81, 0x94, 0xbf, 0x45, 0x1a, 0xb9, 0x2f, 0xf2, 0xb5, 0xad, 0x46, 0x2e, 0x1c,
	0xcd, 0x83, 0x55, 0xc0, 0x43, 0xea, 0xb6, 0xc7, 0xad, 0xc9, 0x90, 0x6c, 0xa5, 0x7f, 0x01, 0x4e,
	0x55, 0x44, 0x26, 0x82, 0x4b, 0xfa, 0x44, 0xac, 0x3b, 0x18, 0xdc, 0x8b, 0x05, 0xe3, 0xcf, 0xcc,
	0xe4, 0x9f, 0xc3, 0xb0, 0xf0, 0x39, 0xa8, 0xec, 0x67, 0x38, 0xbe, 0x8e, 0xa2, 0xbb, 0x8c, 0x47,
	0xf2, 0xa0, 0xf6, 0xa1, 0x53, 0xb0, 0x83, 0xb5, 0xc8, 0xb8, 0x32, 0x95, 0x87, 0xa4, 0x50, 0xfe,
	0x07, 0x70, 0x2a, 0xa3, 0xa2, 0x74, 0xad, 0x3f, 0xad, 0x66, 0x7f, 0x4e, 0x6e, 0x96, 0x34, 0x8c,
	0x67, 0xb9, 0x3e, 0xe0, 0xc4, 0x2d, 0x8c, 0xbe, 0xb1, 0x30, 0xce, 0x92, 0x19, 0x8b, 0xe9, 0x61,
	0x51, 0x11, 0x74, 0xfe, 0x08, 0x4e, 0x8b, 0x16, 0x99, 0xb1, 0xff, 0x11, 0xfa, 0x5f, 0xc5, 0xe6,
	0x19, 0x06, 0x9f, 0x00, 0x7d, 0xe1, 0x3f, 0xc5, 0xcd, 0x8a, 0x51, 0xae, 0xca, 0xdc, 0xa7, 0x60,
	0x0b, 0xae, 0x93, 0x19, 0x93, 0x2e, 0x29, 0x94, 0xe9, 0x96, 0x7a, 0xa8, 0x3c, 0x0a, 0xe5, 0xdf,
	0x43, 0x47, 0x7f, 0x75, 0x85, 0xda, 0x0d, 0x9b, 0x31, 0x3a, 0x01, 0x6b, 0xce, 0x62, 0x2a, 0xcd,
	0x11, 0x8b, 0xe4, 0x42, 0xdf, 0x79, 0x18, 0x24, 0x41, 0xc8, 0xd4, 0xa3, 0x81, 0xcd, 0x22, 0xa5,
	0xf6, 0x2f, 0x60, 0xa4, 0x33, 0x69, 0xc7, 0xaa, 0xf9, 0x6f, 0xc0, 0xd2, 0x81, 0xa5, 0xdb, 0x1a,
	0xb7, 0x27, 0xfd, 0x4b, 0x0b, 0xeb, 0x65, 0x92, 0xcf, 0x5d, 0xfe, 0x6d, 0x43, 0x9f, 0xb0, 0x88,
	0x7e, 0xa7, 0xe9, 0x86, 0x85, 0x14, 0x4d, 0xa1, 0x9b, 0x16, 0xbc, 0x22, 0x07, 0x37, 0xde, 0x87,
	0x37, 0xc2, 0x3b, 0x30, 0xbf, 0x03, 0x6b, 0xa5, 0x31, 0x43, 0x43, 0x5c, 0xc7, 0xd6, 0x7b, 0x89,
	0xff, 0xa7, 0xef, 0x2d, 0xd8, 0x2b, 0xb1, 0x10, 0x99, 0x42, 0x03, 0x5c, 0x7b, 0xa3, 0x9e, 0x8d,
	0xcd, 0xd3, 0xd5, 0x85, 0x83, 0x02, 0x1b, 0xe4, 0xe0, 0x06, 0x8a, 0xde, 0x08, 0xef, 0x30, 0x75,
	0x05, 0x83, 0xb0, 0x46, 0x4e, 0xc3, 0xf6, 0x35, 0xde, 0x8b, 0xd5, 0x04, 0x20, 0x29, 0xe1, 0x41,
	0x08, 0xef, 0x90, 0x54, 0xe6, 0x19, 0x43, 0x37, 0x4a, 0x45, 0xbe, 0x6f, 0x7f, 0xe2, 0x33, 0xe8,
	0xac, 0xc5, 0x46, 0xaf, 0xd6, 0x40, 0xaa, 0xfd, 0x1e, 0x60, 0x25, 0x1e, 0x0d, 0x87, 0x57, 0x78,
	0x0f, 0x39, 0xe7, 0xd0, 0x63, 0xdb, 0xbb, 0x6b, 0xec, 0x47, 0x78, 0xe7, 0x56, 0x67, 0xdd, 0x07,
	0x7b, 0x6a, 0xfe, 0xfd, 0xe6, 0xb6, 0xf9, 0x5c, 0xfd, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x6e, 0x7b,
	0xf8, 0xaf, 0x18, 0x05, 0x00, 0x00,
}
